name: untuk_interview
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  getwidget: ^2.0.4
  popup_banner: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
